### ISSUE TITLE
[rebber] Images command

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#151]
The following MD

    ![](figure.png)

    ![](figure_with_title.png)
    Figure: the figure

    Figure in text: ![](figure.png)

Is translated

```latex
\includegraphics{figure.png}

\begin{center}
    \includegraphics[\linewidth]{figure_with_title.png}
\captionof{figure}{the figure}
\end{center}

Figure in text: \inlineImage{figure.png}
```

Which is correct. But according to  [the documentation](https://github.com/zestedesavoir/latex-template/blob/master/documentation.md#images), that should be

```latex
\image{figure.png}

\image{figure_with_title.png}[the figure]

Figure in text: \inlineImage{figure.png}
```

(or at least in *our* flavor of LaTeX)

**Comment by artragis** [comment]
It is a configuration issue, if the site is not up to date (or the conf incorrect) you won't have image.

**Comment by pierre-24** [comment]
Yeah, maybe it is a configuration issue :-)

**Comment by vhf** [comment]
@pierre-24 https://github.com/zestedesavoir/latex-template/blob/master/test.tex#L136-L139

I'm pretty sure what we do is correct according to your fixtures.

On our side we cannot rely on your [documentation](https://github.com/zestedesavoir/latex-template/blob/master/documentation.md#images) because it misses cases covered by the test fixture, e.g. `\includegraphics[width=…]`
