### ISSUE TITLE
[Question] Any roadmap for supporting abbr?

### ISSUE THREAD

**Issue by cuonghuunguyen** [zestedesavoir/zmarkdown#449]
Hi, thank you for the very nice plugins.

As I see the plugin abbr was broken for a very long time, do you have any plan for fixing it yet? I would be appreciated your update so I can make a decision for choosing my Markdown parser.

Thank you.

**Comment by StaloneLab** [comment]
We are really sorry but no roadmap has been made. As stated in #416 , we plan to migrate our plugins to the new micromark system, but it takes time and effort and we are lacking resources by now.

If you are interested in writing an abbr plugin, however (which would basically means rewriting a completely new plugin), this repo is opened for contributions, and I would be more than happy to help.

**Comment by cuonghuunguyen** [comment]
Hi, thanks for the quick response. Could you tell me where I can find the docs/guide to write a plugin? I tried to find but it seems to be not completed yet

**Comment by StaloneLab** [comment]
I still plan to do a guide, but micromark now has a nice one [in it's documentation](https://github.com/micromark/micromark#creating-a-micromark-extension). You might want to refer to it.

For integration to this repo, please see the branch `next`, where you will find two examples of plugins already ported. Anyway, this step can be done last; if you can experiment with writing a plugin without thinking too much about ZMarkdown, it might be a bit easier.

I will keep this issue open so that you can ask questions should you have any.

**Comment by cuonghuunguyen** [comment]
well, the documentation literally blew my mind 😞 
I wonder if I can reference to sth like this https://github.com/syntax-tree/mdast-util-gfm-footnote

**Comment by StaloneLab** [comment]
Yeah, the new parser has some quite complicated ideas behind it.

What do you mean by sth? The syntax tree?

**Comment by cuonghuunguyen** [comment]
Yes, the syntax tree seems to be similar. I don't know if I can modify something from it to archive the abbr

**Comment by StaloneLab** [comment]
Unfortunately, we have to write the parser that makes the syntax tree. The other part (converting the ST to HTML or something else) is already handled and can mostly be kept as is.
